#ifdef __SEAL_SRS_INFORMATION__ALWAYS_IGNORE  // How to combine an EXP and SRS file
[SRS]
Version=1

[Version]
Major=1
Minor=0
Revision=0
Build=4
AutoIncrementBuild=1

; If AutoIncrementBuild is set to 1, the Build value is increased by 1 every time
; you link the file

[__srs_end]
#endif

DLXUSE_BEGIN
  LIBLOADS_BEGIN
  LIBLOADS_END
  LIBEXPORT_BEGIN
    LIBEXPORT(mp3_init_driver)
    LIBEXPORT(mp3_init_file) 
    LIBEXPORT(mp3_play_file) 
    LIBEXPORT(mp3_poll_file) 
    LIBEXPORT(mp3_stop_file) 
    LIBEXPORT(mp3_pause_file) 
    LIBEXPORT(mp3_forward_file) 
    LIBEXPORT(mp3_rewind_file) 
    LIBEXPORT(mp3_set_pos) 
    LIBEXPORT(mp3_get_pos) 
    LIBEXPORT(mp3_get_len_file) 
    LIBEXPORT(mp3_get_file_info) 
    LIBEXPORT(mp3_get_friendly_name)
    LIBEXPORT(mp3_config_driver)
    LIBEXPORT(mp3_display_about)
    LIBEXPORT(mp3_close_file)
    LIBEXPORT(mp3_terminate_driver)
    LIBEXPORT(mp3_send_custom_message)
//    LIBEXPORT(mp3_pause)
//    LIBEXPORT(PausedPos) 
//    LIBEXPORT(filename) 
//    LIBEXPORT(sound_format_list) 
  LIBEXPORT_END
DLXUSE_END
