#ifdef __SEAL_SRS_INFORMATION__ALWAYS_IGNORE  // How to combine an EXP and SRS file
[SRS]
Version=1

[Version]
Major=0
Minor=3
Revision=1
Build=4
AutoIncrementBuild=1

; If AutoIncrementBuild is set to 1, the Build value is increased by 1 every time
; you link the file

[__srs_end]
#endif

DLXUSE_BEGIN
  LIBLOADS_BEGIN
  LIBLOADS_END
  LIBEXPORT_BEGIN
    LIBEXPORT(mod_init_file)
    LIBEXPORT(mod_play_file)
    LIBEXPORT(mod_poll_file)
    LIBEXPORT(mod_stop_file)
    LIBEXPORT(mod_pause_file)
    LIBEXPORT(mod_forward_file)
    LIBEXPORT(mod_rewind_file)
    LIBEXPORT(mod_set_pos)
    LIBEXPORT(mod_get_pos)
    LIBEXPORT(mod_get_len_file)
    LIBEXPORT(mod_get_file_info)
    LIBEXPORT(mod_get_friendly_name)
    LIBEXPORT(mod_config_driver)
    LIBEXPORT(mod_display_about)
    LIBEXPORT(mod_close_file)
    LIBEXPORT(mod_terminate_driver)
    LIBEXPORT(mod_send_custom_message)
//    LIBEXPORT(filename)
//    LIBEXPORT(sound_format_list) 
  LIBEXPORT_END
DLXUSE_END
