#ifdef __SEAL_SRS_INFORMATION__ALWAYS_IGNORE  // How to combine an EXP and SRS file
[SRS]
Version=1

[Version]
Major=0
Minor=1
Revision=1
Build=4
AutoIncrementBuild=1

; If AutoIncrementBuild is set to 1, the Build value is increased by 1 every time
; you link the file

[__srs_end]
#endif

DLXUSE_BEGIN
  LIBLOADS_BEGIN
  LIBLOADS_END
  LIBEXPORT_BEGIN
    LIBEXPORT(wave_init_driver)
    LIBEXPORT(wave_init_file)
    LIBEXPORT(wave_play_file)
    LIBEXPORT(wave_poll_file)
    LIBEXPORT(wave_stop_file)
    LIBEXPORT(wave_pause_file)
    LIBEXPORT(wave_forward_file)
    LIBEXPORT(wave_rewind_file)
    LIBEXPORT(wave_set_pos)
    LIBEXPORT(wave_get_pos)
    LIBEXPORT(wave_get_len_file)
    LIBEXPORT(wave_get_file_info)
    LIBEXPORT(wave_get_friendly_name)
    LIBEXPORT(wave_config_driver)
    LIBEXPORT(wave_display_about)
    LIBEXPORT(wave_close_file)
    LIBEXPORT(wave_terminate_driver)
    LIBEXPORT(wave_send_custom_message)
  LIBEXPORT_END
DLXUSE_END
